./definition.py etyall a 60
./definition.py etyall b 53
./definition.py etyall c 84
./definition.py etyall d 46
./definition.py etyall e 34
./definition.py etyall f 36
./definition.py etyall g 32
./definition.py etyall h 36
./definition.py etyall i 37
./definition.py etyall j 10
./definition.py etyall k 09
./definition.py etyall l 31
./definition.py etyall m 56
./definition.py etyall n 20
./definition.py etyall o 22
./definition.py etyall p 81
./definition.py etyall q 06
./definition.py etyall r 46
./definition.py etyall s 108
./definition.py etyall t 46
./definition.py etyall u 24
./definition.py etyall v 15
./definition.py etyall w 22
./definition.py etyall x 01
./definition.py etyall y 04
./definition.py etyall z 03
