var actorJSON = {
'nodes': [
'amphitheater',
'a sloping gallery with seats for spectators (as in an operating room or theater)',
'amphitheatre',
'an oval large stadium with tiers of seats; an arena in which contests and spectacles are held',
'coliseum',
'drama',
'a dramatic work intended for performance by actors on a stage',
'play',
'dramatic_play',
'an episode that is turbulent or highly emotional',
'dramatic_event',
'the literary genre of works intended for the theater',
'the quality of being arresting or highly emotional',
'mime',
'an actor who communicates entirely by gesture and facial expression',
'mimer',
'mummer',
'pantomimer',
'pantomimist',
'a performance using gestures and body movements without words',
'pantomime',
'dumb_show',
'imitate (a person or manner), especially for satirical effect',
'mimic',
'act out without words but with gestures and bodily movements only',
'mimicry',
'the act of mimicking; imitative behavior',
'apery',
'the resemblance of an animal species to another species or to natural objects; provides concealment and protection from predators',
'pantomime',
'parody',
'a composition that imitates or misrepresents somebodys style, usually in a humorous way',
'lampoon',
'spoof',
'sendup',
'mockery',
'takeoff',
'burlesque',
'travesty',
'charade',
'pasquinade',
'put-on',
'humorous or satirical mimicry',
'make a spoof of or make fun of',
'make a parody of',
'proscenium',
'the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain)',
'apron',
'forestage',
'the wall that separates the stage from the auditorium in a modern theater',
'proscenium_wall',
'protagonist',
'a person who backs a politician or a team etc.',
'supporter',
'champion',
'admirer',
'booster',
'friend',
'the principal character in a work of fiction',
'agonist',
'saga',
'a narrative telling the adventures of a hero or a family; originally (12th to 14th centuries) a story of the families that settled Iceland and their descendants but now any prose narrative that resembles such an account',
'spoof',
'supernumerary',
'a person serving no apparent function',
'a minor actor in crowd scenes',
'spear_carrier',
'extra',
'more than is needed, desired, or required',
'excess',
'redundant',
'spare',
'supererogatory',
'superfluous',
'surplus',
'thespian',
'a theatrical performer',
'actor',
'histrion',
'player',
'role_player',
'of or relating to drama',
'travesty',
'a comedy characterized by broad satire and improbable situations',
'farce',
'farce_comedy',
'make a travesty of',
'trilogy',
'a set of three literary or dramatic works related in subject or theme',
],
'edges': [

['a sloping gallery with seats for spectators (as in an operating room or theater)','amphitheater'],
['a sloping gallery with seats for spectators (as in an operating room or theater)','amphitheatre'],
['an oval large stadium with tiers of seats; an arena in which contests and spectacles are held','amphitheater'],
['an oval large stadium with tiers of seats; an arena in which contests and spectacles are held','amphitheatre'],
['an oval large stadium with tiers of seats; an arena in which contests and spectacles are held','coliseum'],
['a dramatic work intended for performance by actors on a stage','play'],
['a dramatic work intended for performance by actors on a stage','drama'],
['a dramatic work intended for performance by actors on a stage','dramatic_play'],
['an episode that is turbulent or highly emotional','drama'],
['an episode that is turbulent or highly emotional','dramatic_event'],
['the literary genre of works intended for the theater','drama'],
['the quality of being arresting or highly emotional','drama'],
['an actor who communicates entirely by gesture and facial expression','mime'],
['an actor who communicates entirely by gesture and facial expression','mimer'],
['an actor who communicates entirely by gesture and facial expression','mummer'],
['an actor who communicates entirely by gesture and facial expression','pantomimer'],
['an actor who communicates entirely by gesture and facial expression','pantomimist'],
['a performance using gestures and body movements without words','mime'],
['a performance using gestures and body movements without words','pantomime'],
['a performance using gestures and body movements without words','dumb_show'],
['imitate (a person or manner), especially for satirical effect','mimic'],
['imitate (a person or manner), especially for satirical effect','mime'],
['act out without words but with gestures and bodily movements only','mime'],
['act out without words but with gestures and bodily movements only','pantomime'],
['the act of mimicking; imitative behavior','apery'],
['the act of mimicking; imitative behavior','mimicry'],
['the resemblance of an animal species to another species or to natural objects; provides concealment and protection from predators','mimicry'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','parody'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','lampoon'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','spoof'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','sendup'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','mockery'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','takeoff'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','burlesque'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','travesty'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','charade'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','pasquinade'],
['a composition that imitates or misrepresents somebodys style, usually in a humorous way','put-on'],
['humorous or satirical mimicry','parody'],
['humorous or satirical mimicry','mockery'],
['humorous or satirical mimicry','takeoff'],
['make a spoof of or make fun of','parody'],
['make a parody of','spoof'],
['make a parody of','burlesque'],
['make a parody of','parody'],
['the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain)','proscenium'],
['the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain)','apron'],
['the part of a modern theater stage between the curtain and the orchestra (i.e., in front of the curtain)','forestage'],
['the wall that separates the stage from the auditorium in a modern theater','proscenium'],
['the wall that separates the stage from the auditorium in a modern theater','proscenium_wall'],
['a person who backs a politician or a team etc.','supporter'],
['a person who backs a politician or a team etc.','protagonist'],
['a person who backs a politician or a team etc.','champion'],
['a person who backs a politician or a team etc.','admirer'],
['a person who backs a politician or a team etc.','booster'],
['a person who backs a politician or a team etc.','friend'],
['the principal character in a work of fiction','protagonist'],
['the principal character in a work of fiction','agonist'],
['a narrative telling the adventures of a hero or a family; originally (12th to 14th centuries) a story of the families that settled Iceland and their descendants but now any prose narrative that resembles such an account','saga'],
['a person serving no apparent function','supernumerary'],
['a minor actor in crowd scenes','supernumerary'],
['a minor actor in crowd scenes','spear_carrier'],
['a minor actor in crowd scenes','extra'],
['more than is needed, desired, or required','excess'],
['more than is needed, desired, or required','extra'],
['more than is needed, desired, or required','redundant'],
['more than is needed, desired, or required','spare'],
['more than is needed, desired, or required','supererogatory'],
['more than is needed, desired, or required','superfluous'],
['more than is needed, desired, or required','supernumerary'],
['more than is needed, desired, or required','surplus'],
['a theatrical performer','actor'],
['a theatrical performer','histrion'],
['a theatrical performer','player'],
['a theatrical performer','thespian'],
['a theatrical performer','role_player'],
['of or relating to drama','thespian'],
['a comedy characterized by broad satire and improbable situations','farce'],
['a comedy characterized by broad satire and improbable situations','farce_comedy'],
['a comedy characterized by broad satire and improbable situations','travesty'],
['make a travesty of','travesty'],
['a set of three literary or dramatic works related in subject or theme','trilogy'],
]
};

var r025_humility = {
'nodes': [
'abase',
'cause to feel shame; hurt the pride of',
'humiliate',
'mortify',
'chagrin',
'humble',
'arrogance',
'overbearing pride evidenced by a superior manner toward inferiors',
'haughtiness',
'hauteur',
'high-handedness',
'lordliness',
'cavalier',
'a gallant or courtly gentleman',
'chevalier',
'a royalist supporter of Charles I during the English Civil War',
'Cavalier',
'Royalist',
'given to haughty disregard of others',
'high-handed',
'chagrin',
'strong feelings of embarrassment',
'humiliation',
'mortification',
'ego',
'an inflated feeling of pride in your superiority to others',
'egotism',
'self-importance',
'your consciousness of your own identity',
'self',
'psychoanalysis the conscious mind',
'egoism',
'ethics the theory that the pursuit of your own welfare in the basis of morality',
'concern for your own interests and welfare',
'egocentrism',
'self-interest',
'self-concern',
'self-centeredness',
'egotistical',
'characteristic of those having an inflated idea of their own importance',
'egotistic',
'narcissistic',
'self-loving',
'characteristic of false pride; having an exaggerated sense of self-importance',
'conceited',
'self-conceited',
'swollen',
'swollen-headed',
'vain',
'elated',
'fill with high spirits; fill with optimism',
'elate',
'lift_up',
'uplift',
'pick_up',
'intoxicate',
'exultantly proud and joyful; in high spirits',
'full of high-spirited delight',
'gleeful',
'joyful',
'jubilant',
'haughtiness',
'hubris',
'overbearing pride or presumption',
'humble',
'cause to be unpretentious',
'low or inferior in station or quality',
'low',
'lowly',
'modest',
'small',
'marked by meekness or modesty; not arrogant or prideful',
'used of unskilled work especially domestic work',
'menial',
'of low birth or station `base is archaic in this sense',
'base',
'baseborn',
'humility',
'a disposition to be humble; a lack of false pride',
'humbleness',
'a humble feeling',
'overbearing',
'overcome',
'overbear',
'bear too much',
'contract the abdominal muscles during childbirth to ease delivery',
'bear_down',
'expecting unquestioning obedience',
'authoritarian',
'dictatorial',
'having or showing arrogant superiority to and disdain of those one views as unworthy',
'disdainful',
'haughty',
'imperious',
'lordly',
'prideful',
'sniffy',
'supercilious',
'swaggering',
'pique',
'tightly woven fabric with raised cords',
'a sudden outburst of anger',
'temper',
'irritation',
'cause to feel resentment or indignation',
'offend',
'swarthy',
'naturally having skin of a dark color',
'dark-skinned',
'dusky',
'swart'
],
'edges': [

['cause to feel shame; hurt the pride of','humiliate'],
['cause to feel shame; hurt the pride of','mortify'],
['cause to feel shame; hurt the pride of','chagrin'],
['cause to feel shame; hurt the pride of','humble'],
['cause to feel shame; hurt the pride of','abase'],
['overbearing pride evidenced by a superior manner toward inferiors','arrogance'],
['overbearing pride evidenced by a superior manner toward inferiors','haughtiness'],
['overbearing pride evidenced by a superior manner toward inferiors','hauteur'],
['overbearing pride evidenced by a superior manner toward inferiors','high-handedness'],
['overbearing pride evidenced by a superior manner toward inferiors','lordliness'],
['a gallant or courtly gentleman','cavalier'],
['a gallant or courtly gentleman','chevalier'],
['a royalist supporter of Charles I during the English Civil War','Cavalier'],
['a royalist supporter of Charles I during the English Civil War','Royalist'],
['given to haughty disregard of others','cavalier'],
['given to haughty disregard of others','high-handed'],
['strong feelings of embarrassment','chagrin'],
['strong feelings of embarrassment','humiliation'],
['strong feelings of embarrassment','mortification'],
['an inflated feeling of pride in your superiority to others','ego'],
['an inflated feeling of pride in your superiority to others','egotism'],
['an inflated feeling of pride in your superiority to others','self-importance'],
['your consciousness of your own identity','self'],
['your consciousness of your own identity','ego'],
['psychoanalysis the conscious mind','ego'],
['ethics the theory that the pursuit of your own welfare in the basis of morality','egoism'],
['concern for your own interests and welfare','egoism'],
['concern for your own interests and welfare','egocentrism'],
['concern for your own interests and welfare','self-interest'],
['concern for your own interests and welfare','self-concern'],
['concern for your own interests and welfare','self-centeredness'],
['characteristic of those having an inflated idea of their own importance','egotistic'],
['characteristic of those having an inflated idea of their own importance','egotistical'],
['characteristic of those having an inflated idea of their own importance','narcissistic'],
['characteristic of those having an inflated idea of their own importance','self-loving'],
['characteristic of false pride; having an exaggerated sense of self-importance','conceited'],
['characteristic of false pride; having an exaggerated sense of self-importance','egotistic'],
['characteristic of false pride; having an exaggerated sense of self-importance','egotistical'],
['characteristic of false pride; having an exaggerated sense of self-importance','self-conceited'],
['characteristic of false pride; having an exaggerated sense of self-importance','swollen'],
['characteristic of false pride; having an exaggerated sense of self-importance','swollen-headed'],
['characteristic of false pride; having an exaggerated sense of self-importance','vain'],
['fill with high spirits; fill with optimism','elate'],
['fill with high spirits; fill with optimism','lift_up'],
['fill with high spirits; fill with optimism','uplift'],
['fill with high spirits; fill with optimism','pick_up'],
['fill with high spirits; fill with optimism','intoxicate'],
['exultantly proud and joyful; in high spirits','elated'],
['full of high-spirited delight','elated'],
['full of high-spirited delight','gleeful'],
['full of high-spirited delight','joyful'],
['full of high-spirited delight','jubilant'],
['overbearing pride or presumption','hubris'],
['cause to be unpretentious','humble'],
['low or inferior in station or quality','humble'],
['low or inferior in station or quality','low'],
['low or inferior in station or quality','lowly'],
['low or inferior in station or quality','modest'],
['low or inferior in station or quality','small'],
['marked by meekness or modesty; not arrogant or prideful','humble'],
['used of unskilled work especially domestic work','humble'],
['used of unskilled work especially domestic work','menial'],
['used of unskilled work especially domestic work','lowly'],
['of low birth or station `base is archaic in this sense','base'],
['of low birth or station `base is archaic in this sense','baseborn'],
['of low birth or station `base is archaic in this sense','humble'],
['of low birth or station `base is archaic in this sense','lowly'],
['a disposition to be humble; a lack of false pride','humility'],
['a disposition to be humble; a lack of false pride','humbleness'],
['a humble feeling','humility'],
['a humble feeling','humbleness'],
['overcome','overbear'],
['bear too much','overbear'],
['contract the abdominal muscles during childbirth to ease delivery','bear_down'],
['contract the abdominal muscles during childbirth to ease delivery','overbear'],
['expecting unquestioning obedience','authoritarian'],
['expecting unquestioning obedience','dictatorial'],
['expecting unquestioning obedience','overbearing'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','disdainful'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','haughty'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','imperious'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','lordly'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','overbearing'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','prideful'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','sniffy'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','supercilious'],
['having or showing arrogant superiority to and disdain of those one views as unworthy','swaggering'],
['tightly woven fabric with raised cords','pique'],
['a sudden outburst of anger','pique'],
['a sudden outburst of anger','temper'],
['a sudden outburst of anger','irritation'],
['cause to feel resentment or indignation','pique'],
['cause to feel resentment or indignation','offend'],
['naturally having skin of a dark color','dark-skinned'],
['naturally having skin of a dark color','dusky'],
['naturally having skin of a dark color','swart'],
['naturally having skin of a dark color','swarthy']
]
};

var r026_weakness = {
'nodes': [
'debilitate',
'make weak',
'enfeeble',
'drain',
'droop',
'a shape that sags',
'sag',
'droop, sink, or settle from or as if from pressure or loss of tautness',
'swag',
'flag',
'hang loosely or laxly',
'loll',
'become limp',
'wilt',
'emasculate',
'deprive of strength or vigor',
'castrate',
'remove the testicles of a male animal',
'demasculinize',
'demasculinise',
'having unsuitable feminine qualities',
'effeminate',
'epicene',
'cissy',
'sissified',
'sissyish',
'sissy',
'flaccid',
'drooping without elasticity; wanting in stiffness',
'out of condition; not strong or robust; incapable of exertion or endurance',
'soft',
'flabby',
'foible',
'a behavioral attribute that is distinctive and peculiar to an individual',
'idiosyncrasy',
'mannerism',
'the weaker part of a swords blade from the forte to the tip',
'frail',
'the weight of a frail basket full of raisins or figs; between 50 and 75 pounds',
'a basket for holding dried fruit especially raisins or figs',
'physically weak',
'wanting in moral strength, courage, or will; having the attributes of man as opposed to e.g. divine beings',
'fallible',
'imperfect',
'weak',
'easily broken or damaged or destroyed',
'delicate',
'fragile',
'ineffectual',
'not producing an intended effect',
'ineffective',
'uneffective',
'producing no result or effect',
'futile',
'otiose',
'unavailing',
'lacking in power or forcefulness',
'unable',
'infirmity',
'the state of being weak in health or body especially from old age',
'frailty',
'debility',
'feebleness',
'frailness',
'valetudinarianism',
'invalidate',
'declare invalid',
'annul',
'quash',
'void',
'avoid',
'nullify',
'make invalid for use',
'cancel',
'show to be invalid',
'take away the legal force of or render ineffective',
'vitiate',
'irresolute',
'uncertain how to act or proceed',
'jaded',
'lose interest or become bored with something or somebody',
'tire',
'pall',
'weary',
'fatigue',
'jade',
'exhaust or get tired through overuse or great strain or stress',
'wear_upon',
'tire_out',
'wear',
'wear_out',
'outwear',
'wear_down',
'fag_out',
'fag',
'exhausted',
'wearied',
'dulled by surfeit',
'mealymouthed',
'hesitant to state facts or opinions simply and directly as from e.g. timidity or hypocrisy',
'mealy-mouthed',
'puny',
'inferior in strength or significance',
'used especially of persons of inferior size',
'runty',
'shrimpy',
'succumb',
'consent reluctantly',
'yield',
'give_in',
'knuckle_under',
'buckle_under',
'be fatally overwhelmed',
'vulnerable',
'susceptible to attack',
'susceptible to criticism or persuasion or temptation',
'capable of being wounded or hurt',
'weary',
'physically and mentally fatigued',
'aweary'
],
'edges': [

['make weak','enfeeble'],
['make weak','debilitate'],
['make weak','drain'],
['a shape that sags','sag'],
['a shape that sags','droop'],
['droop, sink, or settle from or as if from pressure or loss of tautness','sag'],
['droop, sink, or settle from or as if from pressure or loss of tautness','droop'],
['droop, sink, or settle from or as if from pressure or loss of tautness','swag'],
['droop, sink, or settle from or as if from pressure or loss of tautness','flag'],
['hang loosely or laxly','droop'],
['hang loosely or laxly','loll'],
['become limp','wilt'],
['become limp','droop'],
['deprive of strength or vigor','emasculate'],
['deprive of strength or vigor','castrate'],
['remove the testicles of a male animal','emasculate'],
['remove the testicles of a male animal','castrate'],
['remove the testicles of a male animal','demasculinize'],
['remove the testicles of a male animal','demasculinise'],
['having unsuitable feminine qualities','effeminate'],
['having unsuitable feminine qualities','emasculate'],
['having unsuitable feminine qualities','epicene'],
['having unsuitable feminine qualities','cissy'],
['having unsuitable feminine qualities','sissified'],
['having unsuitable feminine qualities','sissyish'],
['having unsuitable feminine qualities','sissy'],
['drooping without elasticity; wanting in stiffness','flaccid'],
['out of condition; not strong or robust; incapable of exertion or endurance','soft'],
['out of condition; not strong or robust; incapable of exertion or endurance','flabby'],
['out of condition; not strong or robust; incapable of exertion or endurance','flaccid'],
['a behavioral attribute that is distinctive and peculiar to an individual','idiosyncrasy'],
['a behavioral attribute that is distinctive and peculiar to an individual','foible'],
['a behavioral attribute that is distinctive and peculiar to an individual','mannerism'],
['the weaker part of a swords blade from the forte to the tip','foible'],
['the weight of a frail basket full of raisins or figs; between 50 and 75 pounds','frail'],
['a basket for holding dried fruit especially raisins or figs','frail'],
['physically weak','frail'],
['wanting in moral strength, courage, or will; having the attributes of man as opposed to e.g. divine beings','fallible'],
['wanting in moral strength, courage, or will; having the attributes of man as opposed to e.g. divine beings','frail'],
['wanting in moral strength, courage, or will; having the attributes of man as opposed to e.g. divine beings','imperfect'],
['wanting in moral strength, courage, or will; having the attributes of man as opposed to e.g. divine beings','weak'],
['easily broken or damaged or destroyed','delicate'],
['easily broken or damaged or destroyed','fragile'],
['easily broken or damaged or destroyed','frail'],
['not producing an intended effect','ineffective'],
['not producing an intended effect','uneffective'],
['not producing an intended effect','ineffectual'],
['producing no result or effect','futile'],
['producing no result or effect','ineffectual'],
['producing no result or effect','otiose'],
['producing no result or effect','unavailing'],
['lacking in power or forcefulness','ineffective'],
['lacking in power or forcefulness','ineffectual'],
['lacking in power or forcefulness','unable'],
['the state of being weak in health or body especially from old age','infirmity'],
['the state of being weak in health or body especially from old age','frailty'],
['the state of being weak in health or body especially from old age','debility'],
['the state of being weak in health or body especially from old age','feebleness'],
['the state of being weak in health or body especially from old age','frailness'],
['the state of being weak in health or body especially from old age','valetudinarianism'],
['declare invalid','invalidate'],
['declare invalid','annul'],
['declare invalid','quash'],
['declare invalid','void'],
['declare invalid','avoid'],
['declare invalid','nullify'],
['make invalid for use','cancel'],
['make invalid for use','invalidate'],
['show to be invalid','invalidate'],
['show to be invalid','nullify'],
['take away the legal force of or render ineffective','invalidate'],
['take away the legal force of or render ineffective','void'],
['take away the legal force of or render ineffective','vitiate'],
['uncertain how to act or proceed','irresolute'],
['lose interest or become bored with something or somebody','tire'],
['lose interest or become bored with something or somebody','pall'],
['lose interest or become bored with something or somebody','weary'],
['lose interest or become bored with something or somebody','fatigue'],
['lose interest or become bored with something or somebody','jade'],
['exhaust or get tired through overuse or great strain or stress','tire'],
['exhaust or get tired through overuse or great strain or stress','wear_upon'],
['exhaust or get tired through overuse or great strain or stress','tire_out'],
['exhaust or get tired through overuse or great strain or stress','wear'],
['exhaust or get tired through overuse or great strain or stress','weary'],
['exhaust or get tired through overuse or great strain or stress','jade'],
['exhaust or get tired through overuse or great strain or stress','wear_out'],
['exhaust or get tired through overuse or great strain or stress','outwear'],
['exhaust or get tired through overuse or great strain or stress','wear_down'],
['exhaust or get tired through overuse or great strain or stress','fag_out'],
['exhaust or get tired through overuse or great strain or stress','fag'],
['exhaust or get tired through overuse or great strain or stress','fatigue'],
['exhausted','jaded'],
['exhausted','wearied'],
['dulled by surfeit','jaded'],
['hesitant to state facts or opinions simply and directly as from e.g. timidity or hypocrisy','mealymouthed'],
['hesitant to state facts or opinions simply and directly as from e.g. timidity or hypocrisy','mealy-mouthed'],
['inferior in strength or significance','puny'],
['used especially of persons of inferior size','puny'],
['used especially of persons of inferior size','runty'],
['used especially of persons of inferior size','shrimpy'],
['consent reluctantly','yield'],
['consent reluctantly','give_in'],
['consent reluctantly','succumb'],
['consent reluctantly','knuckle_under'],
['consent reluctantly','buckle_under'],
['be fatally overwhelmed','succumb'],
['be fatally overwhelmed','yield'],
['susceptible to attack','vulnerable'],
['susceptible to criticism or persuasion or temptation','vulnerable'],
['capable of being wounded or hurt','vulnerable'],
['physically and mentally fatigued','aweary'],
['physically and mentally fatigued','weary']
]
};

var r027_satisfaction = {
'nodes': [
'complacency',
'the feeling you have when you are satisfied with yourself',
'complacence',
'self-complacency',
'self-satisfaction',
'complacent',
'contented to a fault with oneself or ones actions',
'self-satisfied',
'self-complacent',
'complaisant',
'showing a cheerful willingness to do favors for others',
'obliging',
'covetous',
'showing extreme cupidity; painfully desirous of anothers advantages',
'envious',
'jealous',
'immoderately desirous of acquiring e.g. wealth',
'avaricious',
'grabby',
'grasping',
'greedy',
'prehensile',
'crave',
'have a craving, appetite, or great desire for',
'hunger',
'thirst',
'starve',
'lust',
'plead or ask for earnestly',
'fruition',
'the condition of bearing fruit',
'enjoyment derived from use or possession',
'something that is made real or concrete',
'realization',
'realisation',
'gloat',
'malicious satisfaction',
'gloating',
'glee',
'dwell on with satisfaction',
'triumph',
'crow',
'gaze at or think about something with great self-satisfaction, gratification, or joy',
'gratify',
'make happy or satisfied',
'satisfy',
'yield to; give satisfaction to',
'pander',
'indulge',
'insatiable',
'impossible to satisfy',
'insatiate',
'unsatiable',
'pander',
'someone who procures customers for whores in England they call a pimp a ponce',
'pimp',
'procurer',
'panderer',
'pandar',
'fancy_man',
'ponce',
'arrange for sexual partners for others',
'procure',
'quench',
'satisfy thirst',
'slake',
'allay',
'assuage',
'put out, as of fires, flames, or lights',
'snuff_out',
'blow_out',
'extinguish',
'electronics: suppress sparking when the current is cut off in an inductive circuit, or suppress an oscillation or discharge in a component or device',
'suppress or crush completely',
'squelch',
'quell',
'reduce the degree of luminescence or phosphorescence in excited molecules or a material by adding a suitable substance',
'cool hot metal by plunging into cold water or other liquid',
'replete',
'fill to satisfaction',
'satiate',
'sate',
'fill',
'filled to satisfaction with food or drink',
'full',
'followed by `withdeeply filled or permeated',
'instinct',
'sate',
'satiate',
'overeat or eat immodestly; make a pig of oneself',
'gorge',
'ingurgitate',
'overindulge',
'glut',
'englut',
'stuff',
'engorge',
'overgorge',
'overeat',
'gormandize',
'gormandise',
'gourmandize',
'binge',
'pig_out',
'scarf_out',
'supplied especially fed to satisfaction',
'satiated',
'slake',
'make less active or intense',
'abate',
'slack',
'cause to heat and crumble by treatment with water',
'smug',
'marked by excessive complacency or self-satisfaction'
],
'edges': [

['the feeling you have when you are satisfied with yourself','complacency'],
['the feeling you have when you are satisfied with yourself','complacence'],
['the feeling you have when you are satisfied with yourself','self-complacency'],
['the feeling you have when you are satisfied with yourself','self-satisfaction'],
['contented to a fault with oneself or ones actions','complacent'],
['contented to a fault with oneself or ones actions','self-satisfied'],
['contented to a fault with oneself or ones actions','self-complacent'],
['showing a cheerful willingness to do favors for others','complaisant'],
['showing a cheerful willingness to do favors for others','obliging'],
['showing extreme cupidity; painfully desirous of anothers advantages','covetous'],
['showing extreme cupidity; painfully desirous of anothers advantages','envious'],
['showing extreme cupidity; painfully desirous of anothers advantages','jealous'],
['immoderately desirous of acquiring e.g. wealth','avaricious'],
['immoderately desirous of acquiring e.g. wealth','covetous'],
['immoderately desirous of acquiring e.g. wealth','grabby'],
['immoderately desirous of acquiring e.g. wealth','grasping'],
['immoderately desirous of acquiring e.g. wealth','greedy'],
['immoderately desirous of acquiring e.g. wealth','prehensile'],
['have a craving, appetite, or great desire for','crave'],
['have a craving, appetite, or great desire for','hunger'],
['have a craving, appetite, or great desire for','thirst'],
['have a craving, appetite, or great desire for','starve'],
['have a craving, appetite, or great desire for','lust'],
['plead or ask for earnestly','crave'],
['the condition of bearing fruit','fruition'],
['enjoyment derived from use or possession','fruition'],
['something that is made real or concrete','realization'],
['something that is made real or concrete','realisation'],
['something that is made real or concrete','fruition'],
['malicious satisfaction','gloat'],
['malicious satisfaction','gloating'],
['malicious satisfaction','glee'],
['dwell on with satisfaction','gloat'],
['dwell on with satisfaction','triumph'],
['dwell on with satisfaction','crow'],
['gaze at or think about something with great self-satisfaction, gratification, or joy','gloat'],
['make happy or satisfied','satisfy'],
['make happy or satisfied','gratify'],
['yield to; give satisfaction to','gratify'],
['yield to; give satisfaction to','pander'],
['yield to; give satisfaction to','indulge'],
['impossible to satisfy','insatiate'],
['impossible to satisfy','insatiable'],
['impossible to satisfy','unsatiable'],
['someone who procures customers for whores in England they call a pimp a ponce','pimp'],
['someone who procures customers for whores in England they call a pimp a ponce','procurer'],
['someone who procures customers for whores in England they call a pimp a ponce','panderer'],
['someone who procures customers for whores in England they call a pimp a ponce','pander'],
['someone who procures customers for whores in England they call a pimp a ponce','pandar'],
['someone who procures customers for whores in England they call a pimp a ponce','fancy_man'],
['someone who procures customers for whores in England they call a pimp a ponce','ponce'],
['arrange for sexual partners for others','pander'],
['arrange for sexual partners for others','pimp'],
['arrange for sexual partners for others','procure'],
['satisfy thirst','quench'],
['satisfy thirst','slake'],
['satisfy thirst','allay'],
['satisfy thirst','assuage'],
['put out, as of fires, flames, or lights','snuff_out'],
['put out, as of fires, flames, or lights','blow_out'],
['put out, as of fires, flames, or lights','extinguish'],
['put out, as of fires, flames, or lights','quench'],
['electronics: suppress sparking when the current is cut off in an inductive circuit, or suppress an oscillation or discharge in a component or device','quench'],
['suppress or crush completely','squelch'],
['suppress or crush completely','quell'],
['suppress or crush completely','quench'],
['reduce the degree of luminescence or phosphorescence in excited molecules or a material by adding a suitable substance','quench'],
['cool hot metal by plunging into cold water or other liquid','quench'],
['fill to satisfaction','satiate'],
['fill to satisfaction','sate'],
['fill to satisfaction','replete'],
['fill to satisfaction','fill'],
['filled to satisfaction with food or drink','full'],
['filled to satisfaction with food or drink','replete'],
['followed by `withdeeply filled or permeated','instinct'],
['followed by `withdeeply filled or permeated','replete'],
['overeat or eat immodestly; make a pig of oneself','gorge'],
['overeat or eat immodestly; make a pig of oneself','ingurgitate'],
['overeat or eat immodestly; make a pig of oneself','overindulge'],
['overeat or eat immodestly; make a pig of oneself','glut'],
['overeat or eat immodestly; make a pig of oneself','englut'],
['overeat or eat immodestly; make a pig of oneself','stuff'],
['overeat or eat immodestly; make a pig of oneself','engorge'],
['overeat or eat immodestly; make a pig of oneself','overgorge'],
['overeat or eat immodestly; make a pig of oneself','overeat'],
['overeat or eat immodestly; make a pig of oneself','gormandize'],
['overeat or eat immodestly; make a pig of oneself','gormandise'],
['overeat or eat immodestly; make a pig of oneself','gourmandize'],
['overeat or eat immodestly; make a pig of oneself','binge'],
['overeat or eat immodestly; make a pig of oneself','pig_out'],
['overeat or eat immodestly; make a pig of oneself','satiate'],
['overeat or eat immodestly; make a pig of oneself','scarf_out'],
['supplied especially fed to satisfaction','satiate'],
['supplied especially fed to satisfaction','satiated'],
['make less active or intense','slake'],
['make less active or intense','abate'],
['make less active or intense','slack'],
['cause to heat and crumble by treatment with water','slack'],
['cause to heat and crumble by treatment with water','slake'],
['marked by excessive complacency or self-satisfaction','smug'],
['marked by excessive complacency or self-satisfaction','self-satisfied']
]
};
var prehensile = {
	'nodes': [
'prehensile',
'adapted for grasping especially by wrapping around an object',
'having a keen intellect',
'immoderately desirous of acquiring e.g. wealth',
'avaricious',
'covetous',
'grabby',
'grasping',
'greedy'
],
'edges': [

['adapted for grasping especially by wrapping around an object','prehensile'],
['having a keen intellect','prehensile'],
['immoderately desirous of acquiring e.g. wealth','avaricious'],
['immoderately desirous of acquiring e.g. wealth','covetous'],
['immoderately desirous of acquiring e.g. wealth','grabby'],
['immoderately desirous of acquiring e.g. wealth','grasping'],
['immoderately desirous of acquiring e.g. wealth','greedy'],
['immoderately desirous of acquiring e.g. wealth','prehensile']
]
};
